services:
  server:
    container_name: teacherop-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production.local
    environment:
      - NODE_ENV=production
      - PORT=3333
      - HOST=0.0.0.0
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=teacherop
      # - DB_PASSWORD=password
      # - DB_DATABASE=teacherop_prod
    command: 'node bin/server.js'
    volumes:
      - server_data:/app\
    ports:
      - '3333:3333'
    restart: on-failure
    networks:
      - teacherop-network
    depends_on:
      - redis
      # - postgres

  # postgres:
  #   container_name: teacherop-postgres
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_USER=teacherop
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=teacherop_prod
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - '5858:5432'
  #   networks:
  #     - teacherop-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -U teacherop']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  jobs:
    container_name: teacherop-jobs
    env_file:
      - .env.production.local
    environment:
      - NODE_ENV=production
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=teacherop
      # - DB_PASSWORD=password
      # - DB_DATABASE=teacherop_prod
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run jobs'
    volumes:
      - jobs_data:/app\
    restart: on-failure
    depends_on:
      - redis
      # - postgres

  redis:
    container_name: teacherop-redis
    image: redis:latest
    ports:
      - '6969:6379'
    volumes:
      - redis_data:/data
    networks:
      - teacherop-network
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

  resque-web:
    image: appwrite/resque-web
    container_name: teacherop-resque-web-prod
    ports:
      - '9696:5678'
    environment:
      - RESQUE_WEB_HOST=redis
      - RESQUE_WEB_PORT=6379
    depends_on:
      - redis
    networks:
      - teacherop-network
    restart: on-failure
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:5678" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

volumes:
  server_data:
  jobs_data:
  redis_data:

networks:
  teacherop-network:
    driver: bridge
