version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - TZ=${TZ}
      - PORT=${PORT}
      - HOST=${HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_KEY=${APP_KEY}
      - NODE_ENV=${NODE_ENV}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DB_POOL_MIN=${DB_POOL_MIN}
      - DB_POOL_MAX=${DB_POOL_MAX}
      - DB_POOL_ACQUIRE=${DB_POOL_ACQUIRE}
      - DB_POOL_IDLE=${DB_POOL_IDLE}
    depends_on:
      - redis
    command: sh -c "cd /app && npm run jobs & cd /app/build && node ace migration:run --force && npm run start"
    healthcheck:
      test: ["CMD", "node", "ace", "db:ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis_data: